using Content.Shared.Corvax.CCCVars;
using Content.Shared.Corvax.TTS;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IConfigurationManager _cfgManager = default!; // CorvaxNext-TTS
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // CorvaxNext-TTS

        private List<TTSVoicePrototype> _voiceList = new(); // CorvaxNext-TTS

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;

            // CorvaxNext-TTS-Start
            if (_cfgManager.GetCVar(CCCVars.TTSEnabled))
            {
                TTSContainer.Visible = true;
                InitializeVoice();
            }
            // CorvaxNext-TTS-End
        }

        // CorvaxNext-TTS-Start
        private void InitializeVoice()
        {
            _voiceList = _prototypeManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

            VoiceButton.AddItem(Loc.GetString("tts-voice-none"));
            VoiceButton.SetItemMetadata(0, "None");

            for (var i = 1; i < _voiceList.Count; i++)
            {
                var name = Loc.GetString(_voiceList[i].Name);
                VoiceButton.AddItem(name);
                VoiceButton.SetItemMetadata(i, _voiceList[i].ID);
            }

            VoiceButton.OnItemSelected += args =>
            {
                VoiceButton.SelectId(args.Id);
            };
        }
        // CorvaxNext-TTS-End

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
            TTSContainer.Visible = ((AdminAnnounceType?) args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station; // CorvaxNext-TTS
        }
    }
}
